
package Controller;

import Dao.mms.implmms;
import Dao.porder.implporder;


/**
 *
 * @author hijus
 */
public class mmsUI_management extends javax.swing.JFrame {

    /**
     * Creates new form mmsUI
     */
    public mmsUI_management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputOrder = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        read = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        deleteID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        read1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        backplatform = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("微軟正黑體", 1, 40)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("管理中心");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 20, 170, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/java_hw4_mms_工作區域 1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        outputOrder.setColumns(20);
        outputOrder.setRows(5);
        jScrollPane1.setViewportView(outputOrder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 500, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        read.setBackground(new java.awt.Color(204, 204, 204));
        read.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        read.setLabel("查詢所有會員資料");
        read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readMouseClicked(evt);
            }
        });
        jPanel2.add(read, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        delete.setText("刪除ID");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        deleteID.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        deleteID.setText("輸入ID");
        deleteID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteIDMouseClicked(evt);
            }
        });
        jPanel2.add(deleteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 500, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        read1.setBackground(new java.awt.Color(204, 204, 204));
        read1.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        read1.setText("查詢所有訂單資料");
        read1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                read1MouseClicked(evt);
            }
        });
        jPanel3.add(read1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        exit.setBackground(new java.awt.Color(204, 204, 204));
        exit.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        exit.setText("離開");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        backplatform.setBackground(new java.awt.Color(204, 204, 204));
        backplatform.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        backplatform.setText("回到控制台");
        backplatform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backplatformMouseClicked(evt);
            }
        });
        jPanel3.add(backplatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 500, 50));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane2.setViewportView(output);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 500, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteIDMouseClicked
        deleteID.setText(null);
    }//GEN-LAST:event_deleteIDMouseClicked

    private void readMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readMouseClicked
       output.setText(new implmms().checkAll());
    }//GEN-LAST:event_readMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
       int ID=Integer.parseInt(deleteID.getText());//TEXT內都是字串 要轉成Int
        new implmms().delete(ID);//這邊是塞數字
        output.setText("已刪除ID:"+ID);
    }//GEN-LAST:event_deleteMouseClicked

    private void read1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read1MouseClicked
        outputOrder.setText(new implporder().checkAllOrder());
    }//GEN-LAST:event_read1MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void backplatformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backplatformMouseClicked
        new platform().setVisible(true);
        this.setVisible(false);//關閉現在這個視窗
    }//GEN-LAST:event_backplatformMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mmsUI_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mmsUI_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mmsUI_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mmsUI_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton backplatform;
    private javax.swing.JButton delete;
    private javax.swing.JTextField deleteID;
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea output;
    private javax.swing.JTextArea outputOrder;
    private javax.swing.JButton read;
    private javax.swing.JButton read1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
            new mmsUI_management().setVisible(true);
        }
    }
}
