/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import Dao.mms.implmms;
import Model.mms;

/**
 *
 * @author hijus
 */
public class mmsUI_update extends javax.swing.JFrame {

    /**
     * Creates new form mmsUI
     */
    public mmsUI_update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        yourID = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        backLogin = new javax.swing.JButton();
        phone = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();
        name2 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        singup_area = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("微軟正黑體", 1, 40)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("資料修改");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 170, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/java_hw4_mms_工作區域 1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        yourID.setBackground(new java.awt.Color(220, 224, 220));
        yourID.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        yourID.setText("查詢會員ID");
        yourID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yourIDMouseClicked(evt);
            }
        });
        getContentPane().add(yourID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, -1));

        jLabel1.setText("-----------請輸入以下需修改的內容-----------");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        update.setBackground(new java.awt.Color(220, 224, 232));
        update.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        update.setText("確定修改");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 470, 140, -1));

        backLogin.setBackground(new java.awt.Color(220, 224, 232));
        backLogin.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        backLogin.setText("回到登入頁面");
        backLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLoginMouseClicked(evt);
            }
        });
        getContentPane().add(backLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 140, -1));

        phone.setText("請輸入您註冊的手機號碼");
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, -1));
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 150, -1));
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, -1));
        getContentPane().add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 150, -1));

        phoneNumber.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        phoneNumber.setText("帳號：");
        getContentPane().add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        password.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        password.setText("密碼：");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        name.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        name.setText("姓名：");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        email.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        email.setText("信箱：");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        singup_area.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/java_hw4_mms_bg-02.png"))); // NOI18N
        getContentPane().add(singup_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 500, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        phone.setText(null);
    }//GEN-LAST:event_phoneMouseClicked

    private void yourIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yourIDMouseClicked
       id.setText(new implmms().phoneCheck(phone.getText()));
       password2.setText(new implmms().phoneCheck2(phone.getText()));
       name2.setText(new implmms().phoneCheck3(phone.getText()));
       email2.setText(new implmms().phoneCheck4(phone.getText()));
    }//GEN-LAST:event_yourIDMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        
        int ID=Integer.parseInt(id.getText());
        String Password=password2.getText();
        String Name=name2.getText();
        String Email=email2.getText();     
        
        mms m=new implmms().queryId(ID);
        m.setPassword(Password);
        m.setName(Name);
        m.setEmail(Email);
        
        new implmms().update(m);
        
        output.setText("資料修改完成囉！");
    }//GEN-LAST:event_updateMouseClicked

    private void backLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLoginMouseClicked
        new logInUI().setVisible(true);
        this.setVisible(false);//關閉現在這個視窗
    }//GEN-LAST:event_backLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mmsUI_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mmsUI_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mmsUI_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mmsUI_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLogin;
    private javax.swing.JLabel background;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email2;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name2;
    private javax.swing.JTextArea output;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel singup_area;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JButton yourID;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
            new mmsUI_update().setVisible(true);
        }
    }
}
