/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import Dao.mms.implmms;
import Model.mms;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hijus
 */
public class signup extends javax.swing.JFrame {

    JFrame frame = new JFrame();
    
    
    public signup() {
        initComponents();
        Date date=new Date();
        SimpleDateFormat sd=new SimpleDateFormat("yyyy/MM/dd");
        String stringDate= sd.format(date);
        signUp.setText(stringDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        signUp = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();
        name2 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        gender2 = new javax.swing.JComboBox<>();
        birth = new javax.swing.JTextField();
        registrationDate = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        singup_area = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("微軟正黑體", 1, 40)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("VIP會員註冊");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 20, 240, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/java_hw4_mms_工作區域 1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        signup.setBackground(new java.awt.Color(220, 224, 232));
        signup.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        signup.setText("確定註冊");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 470, -1, -1));

        update1.setBackground(new java.awt.Color(220, 224, 232));
        update1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        update1.setText("登入頁面");
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update1MouseClicked(evt);
            }
        });
        getContentPane().add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 470, 90, -1));

        update.setBackground(new java.awt.Color(220, 224, 232));
        update.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        update.setText("修改資料");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 470, -1, -1));
        getContentPane().add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, -1));

        phone.setText("請輸入您的手機號碼");
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, -1));
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 150, -1));
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, -1));
        getContentPane().add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, -1));

        gender2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "請選擇", "女性", "男性" }));
        getContentPane().add(gender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, -1));

        birth.setText("格式範例2000/01/01");
        birth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthMouseClicked(evt);
            }
        });
        getContentPane().add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 150, -1));

        registrationDate.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        registrationDate.setText("註冊日：");
        getContentPane().add(registrationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        Number.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        Number.setText("帳號：");
        getContentPane().add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        password.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        password.setText("密碼：");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        name.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        name.setText("姓名：");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        email.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        email.setText("信箱：");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        gender.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        gender.setText("性別：");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        birthday.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        birthday.setText("生日：");
        getContentPane().add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        singup_area.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/java_hw4_mms_bg-02.png"))); // NOI18N
        getContentPane().add(singup_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 500, 70));

        jLabel1.setText("※提醒您，註冊後，性別與生日無法修改，還請輸入正確，避免權益受損！");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void birthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthMouseClicked
        birth.setText(null);
    }//GEN-LAST:event_birthMouseClicked

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        phone.setText(null);
    }//GEN-LAST:event_phoneMouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
         String phoneNumber=phone.getText();
        if(new implmms().query(phoneNumber))
        {
            JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "此手機號碼已註冊\n"+"請重新輸入或返回登入頁面");
        }
        else
        {
        String SignUp=signUp.getText();
        String Phone=phone.getText();
        String Password2=password2.getText();
        String Name=name2.getText();
        String Email2=email2.getText();
        String Gender2=(String) gender2.getSelectedItem();
        String Birth=birth.getText();     
       
       new implmms().add(new mms(SignUp,Phone,Password2,Name,Email2,Gender2,Birth));
       
       output.setText("恭喜您註冊成功，可以登入會員開始購物！"
               + "\n如有需要修改個人資料，可以點選『修改資料』！"
               + "\ndemo時，還請記住輸入的手機號碼，修改資料時會用到！");
    }
        
    }//GEN-LAST:event_signupMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        new mmsUI_update().setVisible(true);//跳到mmsUI_update()視窗
        this.setVisible(false);//關閉現在這個視窗
    }//GEN-LAST:event_updateMouseClicked

    private void update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update1MouseClicked
        new logInUI().setVisible(true);
        this.setVisible(false);//關閉現在這個視窗
    }//GEN-LAST:event_update1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Number;
    private javax.swing.JLabel background;
    private javax.swing.JTextField birth;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email2;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> gender2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name2;
    private javax.swing.JTextArea output;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel registrationDate;
    private javax.swing.JTextField signUp;
    private javax.swing.JButton signup;
    private javax.swing.JLabel singup_area;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
            new signup().setVisible(true);
        }
    }
}
